### PR TITLE
Switched to StaticArrays 

### PR DESCRIPTION
**Pull request by yashcodes**

### CODE REVIEW

**Comment by dpsanders** [comment]
I think you should use SVectors instead of MVectors. But this is something to decide using benchmarks.

Note that IntervalBox is really just an SVector. 

Use broadcasting whenever you can since this is very efficient for static arrays.

**Comment by yashcodes** [comment]
Actually, we cannot update values in Vector which we make by SVector which we need to do, and that cannot be done in Vector using SVector.

**Comment by dpsanders** [comment]
You can use setindex to create a new SVector with one element changed.

**Comment by yashcodes** [comment]
Yes, that's the problem, we need to make a completely new vector to change just one value in an array.

**Pull request merged**
