### PR TITLE
Changed Names and few cleanups

### PR DESCRIPTION
**Pull request by yashcodes**

### CODE REVIEW

**Comment by dpsanders** [comment]
Is filter_elements exported from IntervalOptimisation.jl? If not, it needs to be exported and a new version released in order for travis to pick it up. Please make a PR there.

**Comment by yashcodes** [comment]
In the test by travis.ci according to error `HeapedVector`, `filter_elements!` none of them are exported but in my local machine both of them are exported correctly and everything is working fine.
A new version released ?

**Comment by dpsanders** [comment]
There is a released version of IO.jl, ie the last version that was tagged and submitted to the Julia registry. Are they exported in that version?

**Comment by yashcodes** [comment]
I guess no. We did nothing like that

**Comment by dpsanders** [comment]
So please make a PR to IntervalOptimisation.jl if you need those to be exported

**Comment by dpsanders** [comment]
Please trigger travis and appveyor again. I don't think I have the privileges to do so

**Comment by yashcodes** [comment]
Problem is still same. Did new version of IO.jl is successfully published ?

**Comment by dpsanders** [comment]
It's published now. Please rerun. You can see from the log in Travis that it used v0.3 so it was too early apparently.

**Comment by dpsanders** [comment]
This seems to be ready to be merged!

**Pull request merged**
